name: Release Chinese Kenan Modpack

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15'

      - name: Install Dependency
        run: npm install
      - name: Build Mod
        run: npm start
      - name: Build Wiki
        run: npm run build-wiki

      - uses: montudor/action-zip@v0.1.1
        with:
          args: zip -qq -r Kenan-Modpack-Mod汉化版.zip Kenan-Modpack-Chinese/

      - name: Release Mod
        uses: marvinpinto/action-automatic-releases@v1.1.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: 'latest'
          prerelease: false
          title: '最新CDDA-Kenan-Mod合集汉化版'
          files: |
            Kenan-Modpack-Mod汉化版.zip
      - name: Deploy Tiddlywiki
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public-dist